import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // gettingStartedSidebar: [{type: 'autogenerated', dirName: '.'},],

  //But you can create a sidebar manually
  gettingStartedSidebar: [
      'start/index',
      'start/radix-concepts/index',
      'start/getting-access/index',
      'start/requirements/index',
      'start/config-your-app/index',
      'start/registering-app/index',
      'start/workflows/index',
      'start/radix-clusters/index',
      'start/onboarding/index',
      'start/responsibility/index',
      'start/not-radix/index',
      'start/uptime/index',
      'start/examples/index',

  ],
  guidesSidebar: [
      'guides/index',
      {
        type: 'category',
        label: 'Docker',
        items: [
          'guides/docker/index',
          'guides/docker-useradd/index',
        ],
      },
      {
        type: 'category',
        label: 'CI/CD Pipeline',
        items: [
          'guides/build-and-deploy/index',
          'guides/deploy-only/index',
          'guides/deployment-promotion/index',
          'guides/apply-config/index',
          'guides/sub-pipeline/index',
          'guides/pipeline-badge/index',
        ]
      },
      'guides/build-secrets/index',
      'guides/environment-variables/index',
      {
        type: 'category',
        label: 'Authentication',
        items: [
          'guides/authentication/index',
          'guides/oauth-header-migration-guide/index',
          'guides/workload-identity/index',
        ]
      },
      'guides/azure-key-vaults/index',
      {
        type: 'category',
        label: 'External DNS Alias',
        items: [
          'guides/external-alias/index',
          'guides/external-alias-certificate/index',
        ]
      },
      {
        type: 'category',
        label: 'Jobs',
        items: [
          'guides/jobs/index',
          'guides/jobs/configure-jobs',
            'guides/jobs/job-manager-and-job-api',
            'guides/jobs/notifications',
            'guides/jobs/environment-variables',
            'guides/jobs/jobs-in-web-console',
            'guides/jobs/openapi-swagger',
        ]
      },
      {
        type: 'category',
        label: 'Volume Mounts',
        items: [
          'guides/volume-mounts/index',
          'guides/volume-mounts/limitations',
        ]
      },
      {
          type: 'category',
          label: 'Horizontal Scaling',
          items: [
              'guides/horizontal-scaling/index',
              {
                  type: 'category',
                  label: 'Azure Service Bus',
                  items: [
                      'guides/horizontal-scaling/keda-azure-service-bus-trigger-overview',
                      'guides/horizontal-scaling/keda-azure-service-bus-trigger-authentication',
                  ]
              },
              {
                  type: 'category',
                  label: 'Azure Event Hub',
                  items: [
                      'guides/horizontal-scaling/keda-azure-event-hub-trigger-overview',
                      'guides/horizontal-scaling/keda-azure-event-hub-trigger-authentication',
                      'guides/horizontal-scaling/keda-azure-event-hub-trigger-events',
                  ]
              },
          ]
      },
      'guides/private-link/index',
      'guides/enable-and-disable-components/index',
      'guides/component-start-stop-restart/index',
      'guides/resource-request/index',
      'guides/egress-config/index',
      {
        type: 'category',
        label: 'Monitoring',
        items: [
          'guides/monitoring/index',
          'guides/alerting/index',
        ]
      },
      {
        type: 'category',
        label: 'GitHub',
        items: [
          'guides/git-submodules/index',
          'guides/monorepo/index',
        ]
      }
  ],
  docsSidebar: [
      'docs/index',
      'docs/topic-releases/index',
      'docs/topic-docker/index',
      'docs/topic-runtime-env/index',
      'docs/topic-logs/index',
      'docs/topic-security/index',
      'docs/topic-vulnerabilities/index',
      'docs/topic-monitoring/index',
      'docs/topic-domain-names/index',
      'docs/topic-private-link/index',
      'docs/topic-cost/index',
      'docs/topic-rollingupdate/index',
      'docs/topic-radix-cli/index',
      'docs/topic-code-editor-integration/index',
      'docs/topic-dynatrace-int/index',
      'docs/topic-redis/index',
  ],
  featuresSidebar: [
      'features/index',
  ],
  radixConfigSidebar: [
      'radix-config/index'
  ],
  communitySidebar: [
     'community/index'
  ],
};

export default sidebars;
