services:
  docusaurus:
    image: docker.io/node:20.14.0-alpine3.20
    container_name: docusaurus
    working_dir: /app
    command: ["sh", "-c", "npm run start"]
    profiles:
      - dev
    networks:
      - radix-public-site
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /app

  proxy:
    image: nginxinc/nginx-unprivileged:1.26-alpine
    container_name: proxy
    profiles:
      - dev
    networks:
      - radix-public-site
    ports:
      - "8080:8080"
    depends_on:
      - docusaurus
    volumes:
      - type: bind
        read_only: true
        target: /etc/nginx/conf.d/default.conf
        source: ./proxy/server.dev.conf
      - type: bind
        read_only: true
        target: /etc/nginx/conf.d/securityheaders
        source: ./proxy/securityheaders

  production:
    build:
      context: .
      dockerfile: Dockerfile
    profiles:
      - prod
    ports:
      - "8080:8080"

networks:
  radix-public-site:
    name: radix-public-site
