version: "3.5"

services:
  radix-public-site:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: radix-public-site
    container_name: radix-public-site_container
    networks:
      - radix-public-site
    ports:
      - "8081:3000"

networks:
  radix-public-site:
    name: radix-public-site
