import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // gettingStartedSidebar: [{type: 'autogenerated', dirName: '.'},],

  //But you can create a sidebar manually
  gettingStartedSidebar: [
      {
        type: 'category',
        label: 'Getting started',
        collapsed: false,
        items: [
          'start/index',
          'start/radix-concepts/index',
          'start/getting-access/index',
          'start/requirements/index',
          'start/config-your-app/index',
          'start/registering-app/index',
          'start/workflows/index',
          'start/radix-clusters/index',
          'start/onboarding/index',
        ],
      },
  ],
  guidesSidebar: [
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
          'guides/index',
          'guides/authentication/index',
          'guides/workload-identity/index',
          'guides/docker/index',
          'guides/docker-useradd/index',
          'guides/azure-key-vaults/index',
          'guides/build-secrets/index',
          'guides/environment-variables/index',
          'guides/enable-and-disable-components/index',
          'guides/external-alias/index',
          'guides/component-start-stop-restart/index',
          'guides/jobs/index',
          'guides/deploy-only/index',
          'guides/build-and-deploy/index',
          'guides/deployment-promotion/index',
          'guides/monorepo/index',
          'guides/monitoring/index',
          'guides/resource-request/index',
          'guides/egress-config/index',
          'guides/git-submodules/index',
          'guides/sub-pipeline/index',
          'guides/pipeline-badge/index',
          'guides/alerting/index',
          'guides/volume-mounts/index',
      ],
    }
  ],
  docsSidebar: [
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
          'docs/index',
          'docs/topic-releases/index',
          'docs/topic-docker/index',
          'docs/topic-runtime-env/index',
          'docs/topic-logs/index',
          'docs/topic-security/index',
          'docs/topic-vulnerabilities/index',
          'docs/topic-monitoring/index',
          'docs/topic-domain-names/index',
          'docs/topic-private-link/index',
          'docs/topic-cost/index',
          'docs/topic-rollingupdate/index',
          'docs/topic-uptime/index',
          'docs/topic-radix-cli/index',
          'docs/topic-code-editor-integration/index',
          'docs/topic-dynatrace-int/index',
      ],
    }
  ],
  featuresSidebar: [
      'features/index',
  ],
  radixConfigSidebar: [
      '/docs/radix-config/index'
  ],
  communitySidebar: [
     'community/index'
  ],
};

export default sidebars;
