FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /src
COPY ["Radix.Samples.DotNet.Web/Radix.Samples.DotNet.Web.csproj", "Radix.Samples.DotNet.Web/"]
COPY ["Radix.Samples.Dotnet.Contracts/Radix.Samples.Dotnet.Contracts.csproj", "Radix.Samples.Dotnet.Contracts/"]
RUN dotnet restore "Radix.Samples.DotNet.Web/Radix.Samples.DotNet.Web.csproj"
COPY . .
WORKDIR "/src/Radix.Samples.DotNet.Web"
RUN dotnet build "Radix.Samples.DotNet.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Radix.Samples.DotNet.Web.csproj" -c Release -o /app/publish


FROM  mcr.microsoft.com/dotnet/aspnet:8.0-alpine
WORKDIR /app
COPY --from=publish /app/publish .

EXPOSE 8080
USER 1000
ENTRYPOINT ["dotnet", "Radix.Samples.DotNet.Web.dll"]
