apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-app
spec:
  environments:
    - name: dev
      build:
        from: main
    - name: prod
      build:
        from: release
    - name: demo
  components:
    - name: server
      src: ./backend
      ports:
        - name: http
          port: 3000
      variables:
        PORT: 3000
        GREETING_MESSAGE: "Hello there"
      environmentConfig:
        - environment: prod
          variables:
            GREETING_MESSAGE: "Hello and welcome to the PROD environment"
        - environment: demo
          variables:
            GREETING_MESSAGE: "Hello and welcome to the DEMO environment"
    - name: www
      src: ./frontend
      ports:
        - name: http
          port: 3001
      publicPort: http
      resources:
        requests:
          memory: "50M"
          cpu: "50m"
        limits:
          memory: "50M"
          cpu: "50m"
      variables:
        PORT: 3001
        ECHO_URL: "http://server:3000"
      secrets:
        - DB_PASS
      environmentConfig:
        - environment: prod
          resources:
            requests:
              memory: "250M"
              cpu: "50m"
            limits:
              memory: "500M"
              cpu: "50m"
          replicas: 2
          horizontalScaling:
            minReplicas: 2
            maxReplicas: 5
  dnsAppAlias:
    environment: prod
    component: www